### ISSUE TITLE
Doesn not install properly on PS 1.6.1.1

### ISSUE THREAD

**Issue by summerjob** [firstred/phprediscache#1]
Hi, first of all thanks for making this available.
I'm running PS 1.6.1.1 on NGINX / PHP5-FPM / MySQL (german localisation)

When I upload your module I get a green box "successfully loaded" but no config screen pops up and the module also doens't show up in the module library. In the caching section "redis" also doesn't show next to memcached etc.

I activated redis-server and php5-redis, checked if it's running (ping --> pong) all clear.
Could this be a bug for latest PS or maybe I need to install english language first in order for your module to show up?

**Comment by devdesco-ceo** [comment]
Installed successfully on PS 1.6.1.2 RC3 by manually copying override file "..../override/controllers/admin/AdminPerformanceController.php"

The plugin connects to database "0" on Redis Server, which is not the best choice. Would you please tweak the code to be able to select DB # in module configuration screen? 1+

**Comment by firstred** [comment]
Can you confirm that the override still works? Does it still make a connection with Redis?
In that case I'll have to find a better way to install the override. The normal procedure is rejected by PrestaShop. Caching modules were never meant to be installable, I suppose.

I have a few experiments lying around where you can choose a different db. Let's see if I can merge the code.

**Comment by devdesco-ceo** [comment]
Yes, the override works just fine. I see DB #0 gets populated.

**Comment by firstred** [comment]
The  module has been updated. Tested on vanilla 1.6.1.0, 1.6.1.1 and 1.6.1.2.
You now also have the possibility to select DB.

**Comment by devdesco-ceo** [comment]
Thanks!

**Comment by devdesco-ceo** [comment]
Just updated the module on 1.6.1.2, but I do get these exception messages and there is no connection to the Redis happening since the update. Looks like you did not completely coded the dtabase # selection:

Notice on line 226 in file /var/data/mfs/www/devdesco/ps/modules/phprediscache/phprediscache.php
[8] Undefined index: PREDIS_DB

Notice on line 734 in file /var/data/mfs/www/devdesco/ps/cache/smarty/compile/6e/66/62/6e6662e4bc714906cc0ed98ecbc52cbfb61b676c.file.form.tpl.php
[8] Undefined index: flushdb

Notice on line 734 in file /var/data/mfs/www/devdesco/ps/cache/smarty/compile/6e/66/62/6e6662e4bc714906cc0ed98ecbc52cbfb61b676c.file.form.tpl.php
[8] Undefined index: flushdb

**Comment by firstred** [comment]
`flushdb` is a (Smarty) template variable which has not been set. 
A bit sloppy, but PrestaShop defaults to disabled switches or empty text fields.

`PREDIS_DB` in the `$servers` array is also empty in the beginning, but is, in this case, only used for display and has nothing to do with saving the settings.

Do you have the correct settings in your database (`ps_configuration` table)?

**Comment by devdesco-ceo** [comment]
The problem was that I updated the module through web interface, like all other modules, and I notices, that overrides were not updated. Had to push both files manually over the old ones, and now everything connects to selected database, and populates my redis cache. Thanks a lot!

**Comment by firstred** [comment]
Nice!

The module has to make an unusual override for the file `CachePhpRedis.php`. It makes sense that the module can not always install the file at the unusual location since most people protect the files at `/classes/cache/`. It would save some hassle if the module can detect this and show an error message instead. Good idea for the next version. Thanks for the info!
